import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import StyledComponentsRegistry from "@lib/registry";
import { AppProvider } from "@context/AppContext";
import StyledContext from "@context/StyledContext";
import AppLayout from "@component/layout/AppLayout";
import "../__server__";
import Providers from "Providers/Providers";
import { ToastContainer } from "react-toastify";
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Needibay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/mstile-150x150.png" />
        <meta name="theme-color" content="#672dd1" />
      </head>
      <body className={openSans.className}>
        <Providers>
          <StyledComponentsRegistry>
            <AppProvider>
              <ToastContainer />
              <StyledContext>{children}</StyledContext>
            </AppProvider>
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
